language: csharp
solution: RightTriangleArea.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore RightTriangleArea.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll
